jimi_jimi/account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
	path('register/', views.register, name='register'),
	path('logout/', views.logout, name='logout'),
	path('', include('django.contrib.auth.urls')),
	path('', views.profile, name='profile'),
]

jimi_jimi/jimi_jimi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('video/', include('video.urls', namespace='video')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jimi_jimi/video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
	path('add_video/', views.add_video, name='add_video'),
	path('', views.video_list, name='video_list'),
]

jimi_jimi/account/models.py
from django.db import models

# Create your models here.

jimi_jimi/video/models.py
from django.db import models
from django.contrib.auth.models import User


class Video(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=150)
	description = models.TextField()
	file = models.FileField(upload_to="video/%Y/%m/%d/")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

jimi_jimi/account/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'first_name', 'email']

jimi_jimi/video/forms.py
from django import forms
from .models import Video


class CreateVideoForm(forms.ModelForm):	
	class Meta:
		model = Video
		fields = ['title', 'description', 'file']

jimi_jimi/account/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login, logout as auth_logout
from .forms import UserRegistrationForm


def profile(request):
	return render(request, 'account/profile.html')


def register(request):
	if request.method == 'POST':
		form = UserRegistrationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save(commit=False)
			new_user.set_password(form.cleaned_data['password1'])
			new_user.save()
			messages.success(request, 'Registration completed successfully')
			login(request, new_user)
			return redirect('account:profile')
	else:
		form = UserRegistrationForm()
	return render(request, 'account/register.html', {'form': form})


def logout(request):
	messages.success(request, 'You have successfully logged out')
	auth_logout(request)
	return render(request, 'account/profile.html')

jimi_jimi/video/views.py
import requests
from django.shortcuts import render
from .models import Video
from .forms import CreateVideoForm


def video_list(request):
	all_video = Video.objects.all()
	return render(request, 'video/video_list.html', {'all_video': all_video})


def add_video(request):
	if request.method == 'POST':
		form = CreateVideoForm(request.POST, request.FILES)
		if form.is_valid():
			# Take the transferred file.
			file = request.FILES['file']

			# Create new video.
			new_video = form.save(commit=False)
			new_video.user = request.user

			# Save new video.
			new_video.save()
	else:
		form = CreateVideoForm()
	return render(request, 'video/add_video.html', {'form': form})

jimi_jimi/account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, 	initial-scale=1">
		<title>Jimi Jimi {% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'account/css/base.css' %}">
	</head>
	<body>
		<div id="header">
			<h1>Jimi jimi</h1>

			<!-- Registration information. -->
			<div id="auth">
				{% if user.is_authenticated %}
					<h2>Hello, {{ user.username }}</h2>
					<p><a href="{% url 'account:logout' %}">logout</a></p>
				{% else %}
					<h2><a href="{% url 'account:login' %}">Login</a> or <a href="{% url 'account:register' %}">Register</a></h2>
				{% endif %}
			</div>

			<!-- Display auxiliary messages on the screen. -->
			<div id="messages">
				{% if messages %}
					{% for message in messages %}
						<h3>{{ message }}</h3>
					{% endfor %}
				{% endif %}
			</div>
		</div>

		<div id="content">
			{% block content %}
			{% endblock %}
		</div>

		<div id="footer">
			
		</div>
	</body>
</html>

jimi_jimi/video/templates/video/add_video.html
{% extends 'base.html' %}

{% block title %}
	Add video
{% endblock %}

{% block content %}
	<form method="post" enctype="multipart/form-data">
		{{ form.as_p }}
		{% csrf_token %}
		<input type="submit">
	</form>
{% endblock %}

jimi_jimi/video/templates/video/video_list.html
{% extends 'base.html' %}

{% block title %}
	Video List
{% endblock %}

{% block content %}
	<h2>Video List</h2>
	{% for video in all_video %}
		<video width="320" height="240" controls src="{{video.file.url}}"></video>
		<p>{{ video.title }}</p>
	{% endfor %}
{% endblock %}